/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as OrgRouteImport } from './routes/org'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CarePortalRouteImport } from './routes/care.portal'
import { Route as CareAuthRouteImport } from './routes/care.auth'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppRequestsRouteImport } from './routes/_app.requests'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppOnboardingRouteImport } from './routes/_app.onboarding'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppMapRouteImport } from './routes/_app.map'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppCommunityRouteImport } from './routes/_app.community'
import { Route as AppChatRouteImport } from './routes/_app.chat'
import { Route as AppCareRouteImport } from './routes/_app.care'
import { Route as AppAmbulanceRouteImport } from './routes/_app.ambulance'
import { Route as CarePortalIndexRouteImport } from './routes/care.portal.index'
import { Route as AppProfileIndexRouteImport } from './routes/_app.profile.index'
import { Route as AppCareIndexRouteImport } from './routes/_app.care.index'
import { Route as AppAmbulanceIndexRouteImport } from './routes/_app.ambulance.index'
import { Route as CarePortalOnboardingRouteImport } from './routes/care.portal.onboarding'
import { Route as CarePortalLabRouteImport } from './routes/care.portal.lab'
import { Route as CarePortalDeskRouteImport } from './routes/care.portal.desk'
import { Route as CarePortalAmbulanceRouteImport } from './routes/care.portal.ambulance'
import { Route as AppProfileUserIdRouteImport } from './routes/_app.profile.$userId'
import { Route as AppMeViewRouteImport } from './routes/_app.me.$view'
import { Route as AppChatPeerIdRouteImport } from './routes/_app.chat.$peerId'
import { Route as AppCareLabRouteImport } from './routes/_app.care.lab'
import { Route as AppCareDeskRouteImport } from './routes/_app.care.desk'
import { Route as AppCareAiTestsRouteImport } from './routes/_app.care.ai-tests'
import { Route as AppAmbulanceRequestRouteImport } from './routes/_app.ambulance.request'
import { Route as AppCareTestIdRouteImport } from './routes/_app.care.test.$id'
import { Route as AppCareSerialIdRouteImport } from './routes/_app.care.serial.$id'
import { Route as AppCareLabsOrgIdRouteImport } from './routes/_app.care.labs.$orgId'
import { Route as AppCareLabBookingIdRouteImport } from './routes/_app.care.lab-booking.$id'
import { Route as AppCareDoctorIdRouteImport } from './routes/_app.care.doctor.$id'
import { Route as AppAmbulanceRequestIdRouteImport } from './routes/_app.ambulance.request.$id'
import { Route as AppAmbulanceProviderOrgIdRouteImport } from './routes/_app.ambulance.provider.$orgId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgRoute = OrgRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarePortalRoute = CarePortalRouteImport.update({
  id: '/care/portal',
  path: '/care/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const CareAuthRoute = CareAuthRouteImport.update({
  id: '/care/auth',
  path: '/care/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRequestsRoute = AppRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMapRoute = AppMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunityRoute = AppCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppCareRoute = AppCareRouteImport.update({
  id: '/care',
  path: '/care',
  getParentRoute: () => AppRoute,
} as any)
const AppAmbulanceRoute = AppAmbulanceRouteImport.update({
  id: '/ambulance',
  path: '/ambulance',
  getParentRoute: () => AppRoute,
} as any)
const CarePortalIndexRoute = CarePortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CarePortalRoute,
} as any)
const AppProfileIndexRoute = AppProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProfileRoute,
} as any)
const AppCareIndexRoute = AppCareIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCareRoute,
} as any)
const AppAmbulanceIndexRoute = AppAmbulanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAmbulanceRoute,
} as any)
const CarePortalOnboardingRoute = CarePortalOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => CarePortalRoute,
} as any)
const CarePortalLabRoute = CarePortalLabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => CarePortalRoute,
} as any)
const CarePortalDeskRoute = CarePortalDeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => CarePortalRoute,
} as any)
const CarePortalAmbulanceRoute = CarePortalAmbulanceRouteImport.update({
  id: '/ambulance',
  path: '/ambulance',
  getParentRoute: () => CarePortalRoute,
} as any)
const AppProfileUserIdRoute = AppProfileUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AppProfileRoute,
} as any)
const AppMeViewRoute = AppMeViewRouteImport.update({
  id: '/me/$view',
  path: '/me/$view',
  getParentRoute: () => AppRoute,
} as any)
const AppChatPeerIdRoute = AppChatPeerIdRouteImport.update({
  id: '/$peerId',
  path: '/$peerId',
  getParentRoute: () => AppChatRoute,
} as any)
const AppCareLabRoute = AppCareLabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => AppCareRoute,
} as any)
const AppCareDeskRoute = AppCareDeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => AppCareRoute,
} as any)
const AppCareAiTestsRoute = AppCareAiTestsRouteImport.update({
  id: '/ai-tests',
  path: '/ai-tests',
  getParentRoute: () => AppCareRoute,
} as any)
const AppAmbulanceRequestRoute = AppAmbulanceRequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => AppAmbulanceRoute,
} as any)
const AppCareTestIdRoute = AppCareTestIdRouteImport.update({
  id: '/test/$id',
  path: '/test/$id',
  getParentRoute: () => AppCareRoute,
} as any)
const AppCareSerialIdRoute = AppCareSerialIdRouteImport.update({
  id: '/serial/$id',
  path: '/serial/$id',
  getParentRoute: () => AppCareRoute,
} as any)
const AppCareLabsOrgIdRoute = AppCareLabsOrgIdRouteImport.update({
  id: '/labs/$orgId',
  path: '/labs/$orgId',
  getParentRoute: () => AppCareRoute,
} as any)
const AppCareLabBookingIdRoute = AppCareLabBookingIdRouteImport.update({
  id: '/lab-booking/$id',
  path: '/lab-booking/$id',
  getParentRoute: () => AppCareRoute,
} as any)
const AppCareDoctorIdRoute = AppCareDoctorIdRouteImport.update({
  id: '/doctor/$id',
  path: '/doctor/$id',
  getParentRoute: () => AppCareRoute,
} as any)
const AppAmbulanceRequestIdRoute = AppAmbulanceRequestIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppAmbulanceRequestRoute,
} as any)
const AppAmbulanceProviderOrgIdRoute =
  AppAmbulanceProviderOrgIdRouteImport.update({
    id: '/provider/$orgId',
    path: '/provider/$orgId',
    getParentRoute: () => AppAmbulanceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/org': typeof OrgRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ambulance': typeof AppAmbulanceRouteWithChildren
  '/care': typeof AppCareRouteWithChildren
  '/chat': typeof AppChatRouteWithChildren
  '/community': typeof AppCommunityRoute
  '/home': typeof AppHomeRoute
  '/map': typeof AppMapRoute
  '/notifications': typeof AppNotificationsRoute
  '/onboarding': typeof AppOnboardingRoute
  '/profile': typeof AppProfileRouteWithChildren
  '/requests': typeof AppRequestsRoute
  '/settings': typeof AppSettingsRoute
  '/care/auth': typeof CareAuthRoute
  '/care/portal': typeof CarePortalRouteWithChildren
  '/ambulance/request': typeof AppAmbulanceRequestRouteWithChildren
  '/care/ai-tests': typeof AppCareAiTestsRoute
  '/care/desk': typeof AppCareDeskRoute
  '/care/lab': typeof AppCareLabRoute
  '/chat/$peerId': typeof AppChatPeerIdRoute
  '/me/$view': typeof AppMeViewRoute
  '/profile/$userId': typeof AppProfileUserIdRoute
  '/care/portal/ambulance': typeof CarePortalAmbulanceRoute
  '/care/portal/desk': typeof CarePortalDeskRoute
  '/care/portal/lab': typeof CarePortalLabRoute
  '/care/portal/onboarding': typeof CarePortalOnboardingRoute
  '/ambulance/': typeof AppAmbulanceIndexRoute
  '/care/': typeof AppCareIndexRoute
  '/profile/': typeof AppProfileIndexRoute
  '/care/portal/': typeof CarePortalIndexRoute
  '/ambulance/provider/$orgId': typeof AppAmbulanceProviderOrgIdRoute
  '/ambulance/request/$id': typeof AppAmbulanceRequestIdRoute
  '/care/doctor/$id': typeof AppCareDoctorIdRoute
  '/care/lab-booking/$id': typeof AppCareLabBookingIdRoute
  '/care/labs/$orgId': typeof AppCareLabsOrgIdRoute
  '/care/serial/$id': typeof AppCareSerialIdRoute
  '/care/test/$id': typeof AppCareTestIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/org': typeof OrgRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/chat': typeof AppChatRouteWithChildren
  '/community': typeof AppCommunityRoute
  '/home': typeof AppHomeRoute
  '/map': typeof AppMapRoute
  '/notifications': typeof AppNotificationsRoute
  '/onboarding': typeof AppOnboardingRoute
  '/requests': typeof AppRequestsRoute
  '/settings': typeof AppSettingsRoute
  '/care/auth': typeof CareAuthRoute
  '/ambulance/request': typeof AppAmbulanceRequestRouteWithChildren
  '/care/ai-tests': typeof AppCareAiTestsRoute
  '/care/desk': typeof AppCareDeskRoute
  '/care/lab': typeof AppCareLabRoute
  '/chat/$peerId': typeof AppChatPeerIdRoute
  '/me/$view': typeof AppMeViewRoute
  '/profile/$userId': typeof AppProfileUserIdRoute
  '/care/portal/ambulance': typeof CarePortalAmbulanceRoute
  '/care/portal/desk': typeof CarePortalDeskRoute
  '/care/portal/lab': typeof CarePortalLabRoute
  '/care/portal/onboarding': typeof CarePortalOnboardingRoute
  '/ambulance': typeof AppAmbulanceIndexRoute
  '/care': typeof AppCareIndexRoute
  '/profile': typeof AppProfileIndexRoute
  '/care/portal': typeof CarePortalIndexRoute
  '/ambulance/provider/$orgId': typeof AppAmbulanceProviderOrgIdRoute
  '/ambulance/request/$id': typeof AppAmbulanceRequestIdRoute
  '/care/doctor/$id': typeof AppCareDoctorIdRoute
  '/care/lab-booking/$id': typeof AppCareLabBookingIdRoute
  '/care/labs/$orgId': typeof AppCareLabsOrgIdRoute
  '/care/serial/$id': typeof AppCareSerialIdRoute
  '/care/test/$id': typeof AppCareTestIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/org': typeof OrgRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_app/ambulance': typeof AppAmbulanceRouteWithChildren
  '/_app/care': typeof AppCareRouteWithChildren
  '/_app/chat': typeof AppChatRouteWithChildren
  '/_app/community': typeof AppCommunityRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/map': typeof AppMapRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/onboarding': typeof AppOnboardingRoute
  '/_app/profile': typeof AppProfileRouteWithChildren
  '/_app/requests': typeof AppRequestsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/care/auth': typeof CareAuthRoute
  '/care/portal': typeof CarePortalRouteWithChildren
  '/_app/ambulance/request': typeof AppAmbulanceRequestRouteWithChildren
  '/_app/care/ai-tests': typeof AppCareAiTestsRoute
  '/_app/care/desk': typeof AppCareDeskRoute
  '/_app/care/lab': typeof AppCareLabRoute
  '/_app/chat/$peerId': typeof AppChatPeerIdRoute
  '/_app/me/$view': typeof AppMeViewRoute
  '/_app/profile/$userId': typeof AppProfileUserIdRoute
  '/care/portal/ambulance': typeof CarePortalAmbulanceRoute
  '/care/portal/desk': typeof CarePortalDeskRoute
  '/care/portal/lab': typeof CarePortalLabRoute
  '/care/portal/onboarding': typeof CarePortalOnboardingRoute
  '/_app/ambulance/': typeof AppAmbulanceIndexRoute
  '/_app/care/': typeof AppCareIndexRoute
  '/_app/profile/': typeof AppProfileIndexRoute
  '/care/portal/': typeof CarePortalIndexRoute
  '/_app/ambulance/provider/$orgId': typeof AppAmbulanceProviderOrgIdRoute
  '/_app/ambulance/request/$id': typeof AppAmbulanceRequestIdRoute
  '/_app/care/doctor/$id': typeof AppCareDoctorIdRoute
  '/_app/care/lab-booking/$id': typeof AppCareLabBookingIdRoute
  '/_app/care/labs/$orgId': typeof AppCareLabsOrgIdRoute
  '/_app/care/serial/$id': typeof AppCareSerialIdRoute
  '/_app/care/test/$id': typeof AppCareTestIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/org'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/ambulance'
    | '/care'
    | '/chat'
    | '/community'
    | '/home'
    | '/map'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/requests'
    | '/settings'
    | '/care/auth'
    | '/care/portal'
    | '/ambulance/request'
    | '/care/ai-tests'
    | '/care/desk'
    | '/care/lab'
    | '/chat/$peerId'
    | '/me/$view'
    | '/profile/$userId'
    | '/care/portal/ambulance'
    | '/care/portal/desk'
    | '/care/portal/lab'
    | '/care/portal/onboarding'
    | '/ambulance/'
    | '/care/'
    | '/profile/'
    | '/care/portal/'
    | '/ambulance/provider/$orgId'
    | '/ambulance/request/$id'
    | '/care/doctor/$id'
    | '/care/lab-booking/$id'
    | '/care/labs/$orgId'
    | '/care/serial/$id'
    | '/care/test/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/org'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/chat'
    | '/community'
    | '/home'
    | '/map'
    | '/notifications'
    | '/onboarding'
    | '/requests'
    | '/settings'
    | '/care/auth'
    | '/ambulance/request'
    | '/care/ai-tests'
    | '/care/desk'
    | '/care/lab'
    | '/chat/$peerId'
    | '/me/$view'
    | '/profile/$userId'
    | '/care/portal/ambulance'
    | '/care/portal/desk'
    | '/care/portal/lab'
    | '/care/portal/onboarding'
    | '/ambulance'
    | '/care'
    | '/profile'
    | '/care/portal'
    | '/ambulance/provider/$orgId'
    | '/ambulance/request/$id'
    | '/care/doctor/$id'
    | '/care/lab-booking/$id'
    | '/care/labs/$orgId'
    | '/care/serial/$id'
    | '/care/test/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/admin'
    | '/auth'
    | '/org'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/_app/ambulance'
    | '/_app/care'
    | '/_app/chat'
    | '/_app/community'
    | '/_app/home'
    | '/_app/map'
    | '/_app/notifications'
    | '/_app/onboarding'
    | '/_app/profile'
    | '/_app/requests'
    | '/_app/settings'
    | '/care/auth'
    | '/care/portal'
    | '/_app/ambulance/request'
    | '/_app/care/ai-tests'
    | '/_app/care/desk'
    | '/_app/care/lab'
    | '/_app/chat/$peerId'
    | '/_app/me/$view'
    | '/_app/profile/$userId'
    | '/care/portal/ambulance'
    | '/care/portal/desk'
    | '/care/portal/lab'
    | '/care/portal/onboarding'
    | '/_app/ambulance/'
    | '/_app/care/'
    | '/_app/profile/'
    | '/care/portal/'
    | '/_app/ambulance/provider/$orgId'
    | '/_app/ambulance/request/$id'
    | '/_app/care/doctor/$id'
    | '/_app/care/lab-booking/$id'
    | '/_app/care/labs/$orgId'
    | '/_app/care/serial/$id'
    | '/_app/care/test/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  OrgRoute: typeof OrgRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CareAuthRoute: typeof CareAuthRoute
  CarePortalRoute: typeof CarePortalRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org': {
      id: '/org'
      path: '/org'
      fullPath: '/org'
      preLoaderRoute: typeof OrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/care/portal': {
      id: '/care/portal'
      path: '/care/portal'
      fullPath: '/care/portal'
      preLoaderRoute: typeof CarePortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/care/auth': {
      id: '/care/auth'
      path: '/care/auth'
      fullPath: '/care/auth'
      preLoaderRoute: typeof CareAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/requests': {
      id: '/_app/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof AppRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/map': {
      id: '/_app/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AppMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/community': {
      id: '/_app/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AppCommunityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/care': {
      id: '/_app/care'
      path: '/care'
      fullPath: '/care'
      preLoaderRoute: typeof AppCareRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ambulance': {
      id: '/_app/ambulance'
      path: '/ambulance'
      fullPath: '/ambulance'
      preLoaderRoute: typeof AppAmbulanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/care/portal/': {
      id: '/care/portal/'
      path: '/'
      fullPath: '/care/portal/'
      preLoaderRoute: typeof CarePortalIndexRouteImport
      parentRoute: typeof CarePortalRoute
    }
    '/_app/profile/': {
      id: '/_app/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof AppProfileIndexRouteImport
      parentRoute: typeof AppProfileRoute
    }
    '/_app/care/': {
      id: '/_app/care/'
      path: '/'
      fullPath: '/care/'
      preLoaderRoute: typeof AppCareIndexRouteImport
      parentRoute: typeof AppCareRoute
    }
    '/_app/ambulance/': {
      id: '/_app/ambulance/'
      path: '/'
      fullPath: '/ambulance/'
      preLoaderRoute: typeof AppAmbulanceIndexRouteImport
      parentRoute: typeof AppAmbulanceRoute
    }
    '/care/portal/onboarding': {
      id: '/care/portal/onboarding'
      path: '/onboarding'
      fullPath: '/care/portal/onboarding'
      preLoaderRoute: typeof CarePortalOnboardingRouteImport
      parentRoute: typeof CarePortalRoute
    }
    '/care/portal/lab': {
      id: '/care/portal/lab'
      path: '/lab'
      fullPath: '/care/portal/lab'
      preLoaderRoute: typeof CarePortalLabRouteImport
      parentRoute: typeof CarePortalRoute
    }
    '/care/portal/desk': {
      id: '/care/portal/desk'
      path: '/desk'
      fullPath: '/care/portal/desk'
      preLoaderRoute: typeof CarePortalDeskRouteImport
      parentRoute: typeof CarePortalRoute
    }
    '/care/portal/ambulance': {
      id: '/care/portal/ambulance'
      path: '/ambulance'
      fullPath: '/care/portal/ambulance'
      preLoaderRoute: typeof CarePortalAmbulanceRouteImport
      parentRoute: typeof CarePortalRoute
    }
    '/_app/profile/$userId': {
      id: '/_app/profile/$userId'
      path: '/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof AppProfileUserIdRouteImport
      parentRoute: typeof AppProfileRoute
    }
    '/_app/me/$view': {
      id: '/_app/me/$view'
      path: '/me/$view'
      fullPath: '/me/$view'
      preLoaderRoute: typeof AppMeViewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat/$peerId': {
      id: '/_app/chat/$peerId'
      path: '/$peerId'
      fullPath: '/chat/$peerId'
      preLoaderRoute: typeof AppChatPeerIdRouteImport
      parentRoute: typeof AppChatRoute
    }
    '/_app/care/lab': {
      id: '/_app/care/lab'
      path: '/lab'
      fullPath: '/care/lab'
      preLoaderRoute: typeof AppCareLabRouteImport
      parentRoute: typeof AppCareRoute
    }
    '/_app/care/desk': {
      id: '/_app/care/desk'
      path: '/desk'
      fullPath: '/care/desk'
      preLoaderRoute: typeof AppCareDeskRouteImport
      parentRoute: typeof AppCareRoute
    }
    '/_app/care/ai-tests': {
      id: '/_app/care/ai-tests'
      path: '/ai-tests'
      fullPath: '/care/ai-tests'
      preLoaderRoute: typeof AppCareAiTestsRouteImport
      parentRoute: typeof AppCareRoute
    }
    '/_app/ambulance/request': {
      id: '/_app/ambulance/request'
      path: '/request'
      fullPath: '/ambulance/request'
      preLoaderRoute: typeof AppAmbulanceRequestRouteImport
      parentRoute: typeof AppAmbulanceRoute
    }
    '/_app/care/test/$id': {
      id: '/_app/care/test/$id'
      path: '/test/$id'
      fullPath: '/care/test/$id'
      preLoaderRoute: typeof AppCareTestIdRouteImport
      parentRoute: typeof AppCareRoute
    }
    '/_app/care/serial/$id': {
      id: '/_app/care/serial/$id'
      path: '/serial/$id'
      fullPath: '/care/serial/$id'
      preLoaderRoute: typeof AppCareSerialIdRouteImport
      parentRoute: typeof AppCareRoute
    }
    '/_app/care/labs/$orgId': {
      id: '/_app/care/labs/$orgId'
      path: '/labs/$orgId'
      fullPath: '/care/labs/$orgId'
      preLoaderRoute: typeof AppCareLabsOrgIdRouteImport
      parentRoute: typeof AppCareRoute
    }
    '/_app/care/lab-booking/$id': {
      id: '/_app/care/lab-booking/$id'
      path: '/lab-booking/$id'
      fullPath: '/care/lab-booking/$id'
      preLoaderRoute: typeof AppCareLabBookingIdRouteImport
      parentRoute: typeof AppCareRoute
    }
    '/_app/care/doctor/$id': {
      id: '/_app/care/doctor/$id'
      path: '/doctor/$id'
      fullPath: '/care/doctor/$id'
      preLoaderRoute: typeof AppCareDoctorIdRouteImport
      parentRoute: typeof AppCareRoute
    }
    '/_app/ambulance/request/$id': {
      id: '/_app/ambulance/request/$id'
      path: '/$id'
      fullPath: '/ambulance/request/$id'
      preLoaderRoute: typeof AppAmbulanceRequestIdRouteImport
      parentRoute: typeof AppAmbulanceRequestRoute
    }
    '/_app/ambulance/provider/$orgId': {
      id: '/_app/ambulance/provider/$orgId'
      path: '/provider/$orgId'
      fullPath: '/ambulance/provider/$orgId'
      preLoaderRoute: typeof AppAmbulanceProviderOrgIdRouteImport
      parentRoute: typeof AppAmbulanceRoute
    }
  }
}

interface AppAmbulanceRequestRouteChildren {
  AppAmbulanceRequestIdRoute: typeof AppAmbulanceRequestIdRoute
}

const AppAmbulanceRequestRouteChildren: AppAmbulanceRequestRouteChildren = {
  AppAmbulanceRequestIdRoute: AppAmbulanceRequestIdRoute,
}

const AppAmbulanceRequestRouteWithChildren =
  AppAmbulanceRequestRoute._addFileChildren(AppAmbulanceRequestRouteChildren)

interface AppAmbulanceRouteChildren {
  AppAmbulanceRequestRoute: typeof AppAmbulanceRequestRouteWithChildren
  AppAmbulanceIndexRoute: typeof AppAmbulanceIndexRoute
  AppAmbulanceProviderOrgIdRoute: typeof AppAmbulanceProviderOrgIdRoute
}

const AppAmbulanceRouteChildren: AppAmbulanceRouteChildren = {
  AppAmbulanceRequestRoute: AppAmbulanceRequestRouteWithChildren,
  AppAmbulanceIndexRoute: AppAmbulanceIndexRoute,
  AppAmbulanceProviderOrgIdRoute: AppAmbulanceProviderOrgIdRoute,
}

const AppAmbulanceRouteWithChildren = AppAmbulanceRoute._addFileChildren(
  AppAmbulanceRouteChildren,
)

interface AppCareRouteChildren {
  AppCareAiTestsRoute: typeof AppCareAiTestsRoute
  AppCareDeskRoute: typeof AppCareDeskRoute
  AppCareLabRoute: typeof AppCareLabRoute
  AppCareIndexRoute: typeof AppCareIndexRoute
  AppCareDoctorIdRoute: typeof AppCareDoctorIdRoute
  AppCareLabBookingIdRoute: typeof AppCareLabBookingIdRoute
  AppCareLabsOrgIdRoute: typeof AppCareLabsOrgIdRoute
  AppCareSerialIdRoute: typeof AppCareSerialIdRoute
  AppCareTestIdRoute: typeof AppCareTestIdRoute
}

const AppCareRouteChildren: AppCareRouteChildren = {
  AppCareAiTestsRoute: AppCareAiTestsRoute,
  AppCareDeskRoute: AppCareDeskRoute,
  AppCareLabRoute: AppCareLabRoute,
  AppCareIndexRoute: AppCareIndexRoute,
  AppCareDoctorIdRoute: AppCareDoctorIdRoute,
  AppCareLabBookingIdRoute: AppCareLabBookingIdRoute,
  AppCareLabsOrgIdRoute: AppCareLabsOrgIdRoute,
  AppCareSerialIdRoute: AppCareSerialIdRoute,
  AppCareTestIdRoute: AppCareTestIdRoute,
}

const AppCareRouteWithChildren =
  AppCareRoute._addFileChildren(AppCareRouteChildren)

interface AppChatRouteChildren {
  AppChatPeerIdRoute: typeof AppChatPeerIdRoute
}

const AppChatRouteChildren: AppChatRouteChildren = {
  AppChatPeerIdRoute: AppChatPeerIdRoute,
}

const AppChatRouteWithChildren =
  AppChatRoute._addFileChildren(AppChatRouteChildren)

interface AppProfileRouteChildren {
  AppProfileUserIdRoute: typeof AppProfileUserIdRoute
  AppProfileIndexRoute: typeof AppProfileIndexRoute
}

const AppProfileRouteChildren: AppProfileRouteChildren = {
  AppProfileUserIdRoute: AppProfileUserIdRoute,
  AppProfileIndexRoute: AppProfileIndexRoute,
}

const AppProfileRouteWithChildren = AppProfileRoute._addFileChildren(
  AppProfileRouteChildren,
)

interface AppRouteChildren {
  AppAmbulanceRoute: typeof AppAmbulanceRouteWithChildren
  AppCareRoute: typeof AppCareRouteWithChildren
  AppChatRoute: typeof AppChatRouteWithChildren
  AppCommunityRoute: typeof AppCommunityRoute
  AppHomeRoute: typeof AppHomeRoute
  AppMapRoute: typeof AppMapRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppProfileRoute: typeof AppProfileRouteWithChildren
  AppRequestsRoute: typeof AppRequestsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppMeViewRoute: typeof AppMeViewRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAmbulanceRoute: AppAmbulanceRouteWithChildren,
  AppCareRoute: AppCareRouteWithChildren,
  AppChatRoute: AppChatRouteWithChildren,
  AppCommunityRoute: AppCommunityRoute,
  AppHomeRoute: AppHomeRoute,
  AppMapRoute: AppMapRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppProfileRoute: AppProfileRouteWithChildren,
  AppRequestsRoute: AppRequestsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppMeViewRoute: AppMeViewRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface CarePortalRouteChildren {
  CarePortalAmbulanceRoute: typeof CarePortalAmbulanceRoute
  CarePortalDeskRoute: typeof CarePortalDeskRoute
  CarePortalLabRoute: typeof CarePortalLabRoute
  CarePortalOnboardingRoute: typeof CarePortalOnboardingRoute
  CarePortalIndexRoute: typeof CarePortalIndexRoute
}

const CarePortalRouteChildren: CarePortalRouteChildren = {
  CarePortalAmbulanceRoute: CarePortalAmbulanceRoute,
  CarePortalDeskRoute: CarePortalDeskRoute,
  CarePortalLabRoute: CarePortalLabRoute,
  CarePortalOnboardingRoute: CarePortalOnboardingRoute,
  CarePortalIndexRoute: CarePortalIndexRoute,
}

const CarePortalRouteWithChildren = CarePortalRoute._addFileChildren(
  CarePortalRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  OrgRoute: OrgRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CareAuthRoute: CareAuthRoute,
  CarePortalRoute: CarePortalRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
